version: '3.4'

services:
  microservice2.api:
    image: microservice2api:v3
    build:
      context: .
      dockerfile: Microservice2.API/Dockerfile
  microservice1.api:
    image: microservice1api:v3
    build:
      context: .
      dockerfile: Microservice.API/Dockerfile
  sqlserver_data:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
